version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_DATA_REFRESH_INTERVAL_MINUTES=${REACT_APP_DATA_REFRESH_INTERVAL_MINUTES:-60}
      - REACT_APP_GRID_COLUMNS=${REACT_APP_GRID_COLUMNS:-1}
      # Enable custom CSS overrides using data volume
      - CUSTOM_CSS_PATH=/app/data/custom.css
    volumes:
      # Mount your custom assets directory containing CSS, images, fonts, etc.
      # Update the path on the left to your assets directory location
      - ./data:/app/data:ro
      # Alternative: Mount specific custom assets directory
      # - /path/to/your/custom/assets:/app/data:ro
    depends_on:
      - backend
  backend:
    build: ./backend
    expose:
      - "5100"
    environment:
      - STERN_USERNAME=${STERN_USERNAME}
      - STERN_PASSWORD=${STERN_PASSWORD}
      - DEFAULT_COUNTRY=${DEFAULT_COUNTRY:-US}
      - DEFAULT_STATE=${DEFAULT_STATE:-CO}
      - DEFAULT_STATE_NAME=${DEFAULT_STATE_NAME:-Colorado}
      - DEFAULT_CONTINENT=${DEFAULT_CONTINENT:-NA}
