version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_DATA_REFRESH_INTERVAL_MINUTES=${REACT_APP_DATA_REFRESH_INTERVAL_MINUTES:-60}
      # Enable custom CSS overrides
      - CUSTOM_CSS_PATH=/app/custom-css/overrides.css
    volumes:
      # Mount your custom CSS file (update the path on the left to your CSS file location)
      - ./examples/custom-styles.css:/app/custom-css/overrides.css:ro
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - STERN_USERNAME=${STERN_USERNAME}
      - STERN_PASSWORD=${STERN_PASSWORD}
      - DEFAULT_COUNTRY=${DEFAULT_COUNTRY:-US}
      - DEFAULT_STATE=${DEFAULT_STATE:-CO}
      - DEFAULT_STATE_NAME=${DEFAULT_STATE_NAME:-Colorado}
      - DEFAULT_CONTINENT=${DEFAULT_CONTINENT:-NA}
